resume_from_checkpoint_path: null # only used for resume_from_checkpoint option in PL
result_path: "./result"
pretrained_model_name_or_path: "naver-clova-ix/donut-base" # loading a pre-trained model (from moldehub or path)
dataset_name_or_paths: ["./preprocessed_dataset/training_data"] # loading datasets (from moldehub or path)
sort_json_key: False
train_batch_sizes: 8
val_batch_sizes: 1
input_size: [800, 1000] # when the input resolution differs from the pre-training setting, some weights will be newly initialized (but the model training would be okay)
max_length: 768
align_long_axis: False
num_nodes: 1
lr: 3e-5
warmup_steps: 60 # 800/8*30/10, 10%
max_epochs: 50
max_steps: -1
num_workers: 1
# val_check_interval: 1.0
# check_val_every_n_epoch: 3
gradient_clip_val: 1.0
verbose: True
